name: sayur_widget
description: Helper widget for Sayur
version: 0.0.4
homepage: https://github.com/ronySayur/sayur_widget
repository: null

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.3.0
  card_swiper: ^3.0.1
  day_night_time_picker: ^1.3.0+1
  firebase_crashlytics: ^3.4.8
  flutter:
    sdk: flutter
  flutter_holo_date_picker: ^1.1.3
  fluttertoast: ^8.2.4
  geolocator: ^10.1.0
  http: ^1.1.2
  intl: ^0.19.0
  lottie: ^2.7.0
  no_screenshot: ^0.0.1+6
  path_provider: ^2.1.1
  pie_chart: ^5.4.0
  video_player: ^2.8.1
  flutter_easyloading: ^3.0.5


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/json/
