name: sayur_widget
description: sayur widget is a flutter package
version: 0.0.11
homepage: https://github.com/ronySayur/sayur_widget
repository: https://github.com/ronySayur/sayur_widget

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.3.0
  card_swiper: ^3.0.1
  day_night_time_picker: ^1.3.0+1
  firebase_auth: ^4.16.0
  firebase_crashlytics: ^3.4.8
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_holo_date_picker: ^1.1.3
  flutter_inappwebview: ^5.8.0
  geolocator: ^10.1.0
  google_sign_in: ^6.2.1
  http: ^1.1.2
  image_picker: ^1.0.7
  intl: ^0.17.0
  lottie: ^2.7.0
  no_screenshot: ^0.0.1+6
  path_provider: ^2.1.1
  pie_chart: ^5.4.0
  pinput: ^3.0.1
  shared_preferences: ^2.2.2
  video_player: ^2.8.1
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/json/
