name: sayur_widget
description: sayur widget is a flutter package
version: 0.0.19
homepage: https://github.com/ronySayur/sayur_widget
repository: https://github.com/ronySayur/sayur_widget

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  app_settings: ^5.1.1
  bloc: ^8.1.4
  cached_network_image: ^3.3.0
  card_swiper: ^3.0.1
  day_night_time_picker: ^1.3.0+1
  device_info_plus: ^9.0.3
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  firebase_crashlytics: ^4.0.1
  firebase_messaging: ^15.0.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.6
  flutter_downloader: ^1.11.7
  flutter_easyloading: ^3.0.5
  flutter_html: ^3.0.0-alpha.3F
  flutter_inappwebview: ^5.8.0
  flutter_jailbreak_detection: ^1.10.0
  flutter_local_notifications: ^17.0.0
  flutter_ringtone_player: ^4.0.0+2
  fluttertoast: ^8.2.4
  geolocator: ^12.0.0
  google_sign_in: ^6.2.1
  http: ^1.2.1
  image_picker: ^1.0.7
  internet_connection_checker: ^1.0.0+1
  intl: ^0.17.0
  lottie: ^2.7.0
  no_screenshot: ^0.0.1+6
  package_info_plus: ^6.0.0
  path_provider: ^2.1.1
  permission_handler: ^11.3.1
  pie_chart: ^5.4.0
  pinput: ^3.0.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  video_player: ^2.8.1

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/json/
