name: sayur_widget
description: Helper widget for Sayur
version: 0.0.1
homepage: https://github.com/ronySayur
repository: null

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.3.0
  card_swiper: ^3.0.1
  day_night_time_picker: ^1.3.0+1
  firebase_crashlytics: ^3.4.8
  flutter:
    sdk: flutter
  flutter_holo_date_picker: ^1.1.3
  fluttertoast: ^8.2.4
  geolocator: ^10.1.0
  http: ^1.1.2
  intl: ^0.19.0
  lottie: ^2.7.0
  no_screenshot: ^0.0.1+6
  path_provider: ^2.1.1
  pie_chart: ^5.4.0
  video_player: ^2.8.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/json/
  fonts:
    - family: Satisfy
      fonts:
        - asset: assets/fonts/Satisfy-Regular.ttf
          weight: 500


# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware
# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
